name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - master  # master 브랜치에 푸시될 때마다 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # 프로젝트에 맞는 Node.js 버전 설정

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test  # 테스트 스크립트가 설정되어 있으면 실행

    - name: Build project
      run: npm run build  # 필요한 빌드 작업이 있을 경우

    - name: Deploy to Server
      run: |
        ssh user@3.38.102.20 'cd /path/to/your/project && git pull && npm install && pm2 restart all'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
